// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcN5GNEp5Vh6QU3y3WoMFZ8qbCPr_bvHQ',
    appId: '1:778060244891:web:1461793d719855c24ca33e',
    messagingSenderId: '778060244891',
    projectId: 'my-cool-project-2001',
    authDomain: 'my-cool-project-2001.firebaseapp.com',
    storageBucket: 'my-cool-project-2001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdabuq7gCHFW785lrb6FaxBdDBPCg1up8',
    appId: '1:778060244891:android:c5867f9bf6bb228e4ca33e',
    messagingSenderId: '778060244891',
    projectId: 'my-cool-project-2001',
    storageBucket: 'my-cool-project-2001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAif7iEB9CQA31xiKQO9tcaGB4y8d_3fcA',
    appId: '1:778060244891:ios:6772576e4bdc27054ca33e',
    messagingSenderId: '778060244891',
    projectId: 'my-cool-project-2001',
    storageBucket: 'my-cool-project-2001.firebasestorage.app',
    iosClientId: '778060244891-9skhsfpuuttedushtma2c91qia94bpuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.kuaforRandevuTakipUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAif7iEB9CQA31xiKQO9tcaGB4y8d_3fcA',
    appId: '1:778060244891:ios:6772576e4bdc27054ca33e',
    messagingSenderId: '778060244891',
    projectId: 'my-cool-project-2001',
    storageBucket: 'my-cool-project-2001.firebasestorage.app',
    iosClientId: '778060244891-9skhsfpuuttedushtma2c91qia94bpuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.kuaforRandevuTakipUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcN5GNEp5Vh6QU3y3WoMFZ8qbCPr_bvHQ',
    appId: '1:778060244891:web:378a340611470e8d4ca33e',
    messagingSenderId: '778060244891',
    projectId: 'my-cool-project-2001',
    authDomain: 'my-cool-project-2001.firebaseapp.com',
    storageBucket: 'my-cool-project-2001.firebasestorage.app',
  );
}
